### ISSUE TITLE
Broken API

### ISSUE THREAD

**Issue by Jimmy-Newtron** [jzcling/react-material-ui-form-builder#5]
While trying to use the library (following the README) I got compilation errors.

I saw that you are committing a lot of changes to include/use the react-hook-form (https://react-hook-form.com/)

Can you provide information on when a new version will be stable?
Can you update the README?

How can we contribute to this project?

Thanks in advance

**Comment by jzcling** [comment]
I've just updated the README to work with the latest version (1.1.2) that I just pushed. 

I've been rewriting the library in Typescript and refactoring to use react-hook-form to increase performance and it's quite a big mess right now, especially the type definitions.

In terms of functionality, the refactored version only lacks the rarely used drag and drop feature that the autocomplete component used to have, mostly because there doesn't seem to be a way to dynamically import named exports with the loadable components library.

I've been very careless with my pushes and haven't maintained a changelog as I didn't think anyone else would be using the library, but going forward I can commit to being more disciplined with testing and start to populate a changelog.

All that said, would be really grateful if anyone could help with cleaning up the types and writing some automated tests. The library is currently very tightly coupled with the MUI components so tests may be difficult to write.

Otherwise, if there is any other functionality you'd like to see in the library, feel free to suggest and contribute!
